---
settings:
  name: BlueXP tiering
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di tiering BlueXP
    url: "/index.html"
  - title: Note di rilascio
    url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sul tiering BlueXP
      url: "/concept-cloud-tiering.html"
    - title: Tiering on-premise dei dati nel cloud
      entries:
      - title: Tier to Amazon S3
        url: "/task-tiering-onprem-aws.html"
      - title: Tier to Azure Blob storage
        url: "/task-tiering-onprem-azure.html"
      - title: Tier to Google Cloud Storage
        url: "/task-tiering-onprem-gcp.html"
      - title: Tier to StorageGRID
        url: "/task-tiering-onprem-storagegrid.html"
      - title: Tier allo storage a oggetti S3
        url: "/task-tiering-onprem-s3-compat.html"
    - title: Impostare la licenza
      url: "/task-licensing-cloud-tiering.html"
    - title: FAQ
      url: "/faq-cloud-tiering.html"
  - title: Utilizza il tiering BlueXP
    entries:
    - title: Gestire il tiering dei dati
      url: "/task-managing-tiering.html"
    - title: Gestire lo storage a oggetti
      url: "/task-managing-object-storage.html"
    - title: Test delle performance del cloud
      url: "/task-tiering-test.html"
    - title: Visualizza la panoramica del tiering per tutti i cluster
      url: "/task-tiering-onprem-overview.html"
    - title: Monitorare lo stato degli avvisi di tiering
      url: "/task-monitor-tiering-alerts.html"
  - title: Riferimento
    entries:
    - title: Classi e regioni di storage Amazon S3 supportate
      url: "/reference-aws-support.html"
    - title: Aree geografiche e livelli di accesso Azure supportati
      url: "/reference-azure-support.html"
    - title: Classi e regioni di storage Google Cloud supportate
      url: "/reference-google-support.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Scopri di più sul tiering BlueXP
      url: concept-cloud-tiering.html
    - title: Novità
      url: whats-new.html
    - title: Impostare la licenza
      url: task-licensing-cloud-tiering.html
  - title: Eseguire il Tier on-premise dei dati ONTAP nel cloud
    links:
    - title: Tier to Amazon S3
      url: task-tiering-onprem-aws.html
    - title: Tier to Azure Blob
      url: task-tiering-onprem-azure.html
    - title: Tier to Google Cloud
      url: task-tiering-onprem-gcp.html
    - title: Tier to StorageGRID
      url: task-tiering-onprem-storagegrid.html
    - title: Tier to generic S3
      url: task-tiering-onprem-s3-compat.html
  - title: Gestire le impostazioni di tiering
    links:
    - title: Modificare la policy di tiering di un volume
      url: task-managing-tiering.html#changing-a-volumes-tiering-policy
    - title: Esaminare le informazioni di tiering per un cluster
      url: task-managing-tiering.html#reviewing-tiering-info-for-a-cluster
    - title: Dati Tier da volumi aggiuntivi
      url: task-managing-tiering.html#tiering-data-from-additional-volumes
    - title: Modificare la larghezza di banda per caricare i dati inattivi nello storage
        a oggetti
      url: task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage
    - title: Spostare di nuovo i dati dal cloud al Tier di performance
      url: task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier
    - title: Gestire le impostazioni di tiering sugli aggregati
      url: task-managing-tiering.html#managing-tiering-settings-on-aggregates
  - title: Gestire lo storage a oggetti
    links:
    - title: Aggiungere un nuovo archivio di oggetti per un cluster
      url: task-managing-object-storage.html#adding-a-new-object-store
    - title: Aggiungere un secondo archivio di oggetti a un aggregato per il mirroring
      url: task-managing-object-storage.html#attaching-a-second-object-store-to-an-aggregate-for-mirroring
    - title: Sostituire l'archivio di oggetti primario e mirror
      url: task-managing-object-storage.html#swapping-the-primary-and-mirror-object-store
    - title: Rimuovere un archivio di oggetti mirror
      url: task-managing-object-storage.html#removing-a-mirror-object-store-from-an-aggregate
  - title: Blog e community
    links:
    - title: Community NetApp
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: Blog BlueXP Tiering
      url: https://bluexp.netapp.com/blog/topic/cloud-tiering
    - title: Webinar sul cloud
      url: https://bluexp.netapp.com/events
  - title: Altre risorse
    links:
    - title: Casi di utilizzo di BlueXP
      url: https://bluexp.netapp.com/cloud-tiering
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Tutta la documentazione BlueXP
