---
settings:
  name: BlueXP tiering
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti di tiering BlueXP
    url: "/index.html"
  - title: Note di rilascio
    url: "/whats-new.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più sul tiering BlueXP
      url: "/concept-cloud-tiering.html"
    - title: Tiering on-premise dei dati nel cloud
      entries:
      - title: Tier to Amazon S3
        url: "/task-tiering-onprem-aws.html"
      - title: Tier to Azure Blob storage
        url: "/task-tiering-onprem-azure.html"
      - title: Tier to Google Cloud Storage
        url: "/task-tiering-onprem-gcp.html"
      - title: Tier to StorageGRID
        url: "/task-tiering-onprem-storagegrid.html"
      - title: Tier allo storage a oggetti S3
        url: "/task-tiering-onprem-s3-compat.html"
    - title: Impostare la licenza
      url: "/task-licensing-cloud-tiering.html"
    - title: FAQ
      url: "/faq-cloud-tiering.html"
  - title: Utilizza il tiering BlueXP
    entries:
    - title: Gestire il tiering dei dati
      url: "/task-managing-tiering.html"
    - title: Gestire lo storage a oggetti
      url: "/task-managing-object-storage.html"
    - title: Test delle performance del cloud
      url: "/task-tiering-test.html"
    - title: Visualizza la panoramica del tiering per tutti i cluster
      url: "/task-tiering-onprem-overview.html"
    - title: Monitorare lo stato degli avvisi di tiering
      url: "/task-monitor-tiering-alerts.html"
  - title: Riferimento
    entries:
    - title: Classi e regioni di storage Amazon S3 supportate
      url: "/reference-aws-support.html"
    - title: Aree geografiche e livelli di accesso Azure supportati
      url: "/reference-azure-support.html"
    - title: Classi e regioni di storage Google Cloud supportate
      url: "/reference-google-support.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
