---
sidebar: sidebar 
permalink: reference-azure-support.html 
keywords: microsoft azure, azure, hot, access tier, cold, regions 
summary: BlueXP Tiering supporta due livelli di accesso e la maggior parte delle regioni. 
---
= Aree e livelli di accesso supportati da Azure Blob
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP Tiering supporta due livelli di accesso e la maggior parte delle regioni.



== Livelli di accesso supportati da Azure Blob

Quando configuri il tiering dei dati in Azure dai sistemi ONTAP on-premise, il tiering di BlueXP utilizza automaticamente il Tier di accesso _Hot_ per i dati inattivi. BlueXP Tiering può applicare una regola del ciclo di vita in modo che i dati transitino dal Tier di accesso _Hot_ al Tier di accesso _Cool_ dopo un certo numero di giorni.

Se non si sceglie il livello di accesso _Cool_, i dati rimangono nel livello di accesso _Hot_ e non vengono applicate regole.

Quando si configura una regola del ciclo di vita del tiering BlueXP, non è necessario configurare alcuna regola del ciclo di vita durante la configurazione del container nell'account Azure.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Scopri i Tier di accesso di Azure Blob"^].



== Aree Azure supportate

Il tiering di BlueXP  supporta le seguenti aree Azure. Le regioni Azure Cina non sono supportate come destinazioni per il tiering.



=== Africa

* Sud Africa, Nord




=== Asia Pacifico

* Australia Est
* Australia sud-orientale
* Asia orientale
* Giappone Est
* Giappone occidentale
* Corea centrale
* Corea del Sud
* Sud-est asiatico




=== Europa

* Francia centrale
* Germania Centro Ovest
* Germania Nord
* Nord Europa
* Regno Unito sud
* Regno Unito, ovest
* Europa occidentale




=== Nord America

* Canada centrale
* Canada Est
* Stati Uniti centrali
* Stati Uniti orientali
* Est US 2
* Stati Uniti centro-nord
* Stati Uniti centro-sud
* Stati Uniti occidentali
* US 2 ovest
* Stati Uniti centro-occidentali




=== America del Sud

* Brasile Sud

