---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, tiering' 
summary: Scopri le novità di BlueXP Tiering. 
---
= Novità del tiering BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità di BlueXP Tiering.



== 3 aprile 2023



=== La scheda Licensing (licenze) è stata rimossa

La scheda Licensing (licenze) è stata rimossa dall'interfaccia di tiering BlueXP. Tutte le licenze per gli abbonamenti pay-as-you-go (PAYGO) sono accessibili subito dal pannello di controllo on-premise di BlueXP Tiering. Da questa pagina è inoltre disponibile un collegamento al portafoglio digitale BlueXP, che consente di visualizzare e gestire qualsiasi tipo di licenza BYOL (Bring-Your-Own-licenses) BlueXP tiering.



=== Le schede di tiering sono state rinominate e il contenuto è stato aggiornato

La scheda "Clusters Dashboard" è stata rinominata "Clusters" e la scheda "on-Prem Overview" è stata rinominata "on-premise Dashboard". In queste pagine sono state aggiunte alcune informazioni utili per valutare se è possibile ottimizzare lo spazio di storage con una configurazione di tiering aggiuntiva.



== 5 marzo 2023



=== Ora è possibile generare un report di tiering per i volumi

È possibile scaricare un report dalla pagina Tier Volumes per esaminare lo stato di tiering di tutti i volumi nei cluster che si stanno gestendo. BlueXP Tiering genera un file .CSV che è possibile rivedere e inviare ad altre persone dell'azienda in base alle necessità. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#download-a-tiering-report-for-your-volumes["Scopri come scaricare il report sul tiering"].



== 6 dicembre 2022



=== Modifiche degli endpoint di accesso a Internet in uscita del connettore

A causa di una modifica nel tiering BlueXP, è necessario modificare i seguenti endpoint del connettore per eseguire correttamente il tiering BlueXP:

[cols="50,50"]
|===
| Vecchio endpoint | Nuovo endpoint 


| https://cloudmanager.cloud.netapp.com | https://api.bluexp.netapp.com 


| https://*.cloudmanager.cloud.netapp.com | https://*.api.bluexp.netapp.com 
|===
Consulta l'elenco completo degli endpoint per il https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^], o. https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] ambiente cloud.



== 6 novembre 2022



=== Trascinare e rilasciare per abilitare il tiering BlueXP su Azure Blob, Google Cloud Storage e StorageGRID

Se la destinazione Azure Blob, Google Cloud Storage o StorageGRID Tiering esiste come ambiente di lavoro su Canvas, è possibile trascinare l'ambiente di lavoro on-premise ONTAP sulla destinazione per avviare la configurazione guidata del tiering.



== 19 settembre 2022



=== La procedura guidata di tiering consente di configurare AWS PrivateLink quando si esegue il tiering sullo storage S3

Nelle release precedenti era molto dispendioso in termini di tempo fornire questo modo sicuro di connettere il cluster a un bucket S3 attraverso un endpoint VPC. A questo punto, è possibile seguire i passaggi richiesti per https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#configure-your-system-for-a-private-connection-using-a-vpc-endpoint-interface["Configurare il sistema per una connessione privata utilizzando un'interfaccia endpoint VPC"], Quindi selezionare PrivateLink durante l'installazione guidata del tiering nella pagina rete.

https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html["Consulta i requisiti e i passaggi per il Tier dei dati inattivi su Amazon S3"].



=== Trascinare e rilasciare per abilitare il tiering BlueXP su Amazon S3

Se la destinazione del tiering Amazon S3 esiste come ambiente di lavoro su Canvas, è possibile trascinare l'ambiente di lavoro ONTAP on-premise sulla destinazione per avviare la configurazione guidata del tiering.



=== Scegliere il comportamento del tiering quando si rimuove l'archivio di oggetti mirror in una configurazione MetroCluster

Quando si rimuove l'archivio di oggetti mirror da una configurazione MetroCluster, viene richiesto se si desidera rimuovere anche l'archivio di oggetti primario. È possibile scegliere di mantenere l'archivio di oggetti primario collegato all'aggregato o di rimuoverlo.



== 3 agosto 2022



=== Possibilità di configurare archivi di oggetti aggiuntivi per altri aggregati nel cluster

L'interfaccia utente Cloud Tiering ha aggiunto un nuovo set di pagine per la configurazione dello storage a oggetti. È possibile aggiungere nuovi archivi di oggetti, connettere più archivi di oggetti a un aggregato per il mirroring FabricPool, scambiare gli archivi di oggetti primari e mirror, eliminare le connessioni degli archivi di oggetti agli aggregati e molto altro ancora. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-object-storage.html["Scopri di più sulla nuova funzionalità di storage a oggetti."]



=== Supporto delle licenze Cloud Tiering per le configurazioni MetroCluster

Le licenze Cloud Tiering possono ora essere condivise con i cluster che si trovano in configurazioni MetroCluster. Non è più necessario utilizzare le licenze FabricPool obsolete per questi scenari. In questo modo è più semplice utilizzare le licenze di Cloud Tiering "fluttuanti" su più cluster. https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["Scopri come concedere in licenza e configurare questi tipi di cluster."]



== 3 maggio 2022



=== Supporto della licenza Cloud Tiering per ulteriori configurazioni cluster

Le licenze Cloud Tiering possono ora essere condivise con i cluster che si trovano nelle configurazioni Tiering Mirror (non incluse le configurazioni MetroCluster) e con i cluster che sono Tiered per lo storage a oggetti cloud IBM. Non è più necessario utilizzare le licenze FabricPool obsolete per questi scenari. In questo modo è più semplice utilizzare le licenze di Cloud Tiering "fluttuanti" su più cluster. https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html#apply-bluexp-tiering-licenses-to-clusters-in-special-configurations["Scopri come concedere in licenza e configurare questi tipi di cluster."]



== 4 aprile 2022



=== È ora disponibile la classe di storage Amazon S3 Glacier Instant Retrieval

Quando si imposta il Cloud Tiering, è ora possibile configurare una regola del ciclo di vita in modo che i dati inattivi passino dalla classe di storage _Standard_ a _Glacier Instant Retrieval_ dopo un certo numero di giorni. In questo modo si riducono i costi dell'infrastruttura AWS. https://docs.netapp.com/us-en/bluexp-tiering/reference-aws-support.html["Consulta le classi di storage S3 supportate."]



=== Il cloud tiering è stato pienamente qualificato per i sistemi ONTAP Select

Oltre al tiering dei dati dai sistemi AFF e FAS, ora puoi tierare i dati inattivi dai sistemi ONTAP Select allo storage cloud.
